# Generated by Django 4.2.1 on 2023-05-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_card_no",
                    models.CharField(max_length=18, verbose_name="id_card_no"),
                ),
                ("exam_id", models.IntegerField(max_length=11, verbose_name="exam_id")),
                (
                    "enrollment_time",
                    models.DateTimeField(verbose_name="enrollment_time"),
                ),
                (
                    "payment_status",
                    models.CharField(max_length=20, verbose_name="payment_status"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_card_no",
                    models.CharField(max_length=18, verbose_name="id_card_no"),
                ),
                ("exam_id", models.IntegerField(max_length=11, verbose_name="exam_id")),
                ("payment_time", models.DateTimeField(verbose_name="payment_time")),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="payment_amount"
                    ),
                ),
            ],
        ),
    ]
