# Generated by Django 4.1 on 2023-06-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_admin_examinee_examinformation_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="enrollment",
            table="enrollment",
        ),
        migrations.AlterModelTable(
            name="payment",
            table="payment",
        ),
    ]
