# Generated by Django 4.2.1 on 2023-06-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamInformation",
            fields=[
                ("exam_id", models.IntegerField(primary_key=True, serialize=False)),
                ("exam_name", models.CharField(blank=True, max_length=50, null=True)),
                ("exam_time", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "exam_information",
                "managed": True,
            },
        ),
    ]
