# Generated by Django 4.1 on 2023-06-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("take_exam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectiveanswers",
            name="examinee_id",
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name="subjectiveanswers",
            name="examinee_id",
            field=models.CharField(max_length=18),
        ),
        migrations.AlterUniqueTogether(
            name="objectiveanswers",
            unique_together={("examinee_id", "paper_id", "question_id")},
        ),
        migrations.AlterUniqueTogether(
            name="subjectiveanswers",
            unique_together={("examinee_id", "paper_id", "question_id")},
        ),
    ]
