# Generated by Django 4.2.1 on 2023-06-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamInformation",
            fields=[
                ("exam_id", models.IntegerField(primary_key=True, serialize=False)),
                ("exam_name", models.CharField(blank=True, max_length=50, null=True)),
                ("exam_time", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "exam_information",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id_card_no",
                    models.CharField(max_length=18, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "admin",
            },
        ),
        migrations.CreateModel(
            name="Examinee",
            fields=[
                (
                    "id_card_no",
                    models.CharField(max_length=18, primary_key=True, serialize=False),
                ),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
            ],
            options={
                "db_table": "examinee",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id_card_no",
                    models.OneToOneField(
                        db_column="id_card_no",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="User_Manage.examinee",
                    ),
                ),
                ("enrollment_time", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "db_table": "enrollment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExamScore",
            fields=[
                (
                    "id_card_no",
                    models.OneToOneField(
                        db_column="id_card_no",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="User_Manage.examinee",
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("publish_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "exam_score",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id_card_no",
                    models.OneToOneField(
                        db_column="id_card_no",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="User_Manage.examinee",
                    ),
                ),
                ("payment_time", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "payment",
                "managed": False,
            },
        ),
    ]
